### ISSUE TITLE
http://testng.org/doc/download.html not get updated

### ISSUE THREAD

**Issue by missedone** [testng-team/testng-team.github.io#11]
hi @cbeust , @juherr 
the page http://testng.org/doc/download.html not get updated even after the PR #10 "update testng version to 6.9.12" merged.
it still pointing to 6.9.10.
could you have a check on this?

**Comment by juherr** [comment]
:+1: 
And https://api.bintray.com/packages/cbeust/maven/testng/versions/_latest will provide an always up2date value.

```json
{
  "name": "6.9.12",
  "desc": null,
  "package": "testng",
  "repo": "maven",
  "owner": "cbeust",
  "labels": [
    "java",
    "testing"
  ],
  "attribute_names": [],
  "created": "2016-06-21T18:18:03.784Z",
  "updated": "2016-06-21T18:19:00.157Z",
  "released": "",
  "ordinal": 58
}
```

**Comment by missedone** [comment]
closed since the page got updated now
