### ISSUE TITLE
Missing documentation: All authorized return types of a DataProvider method

### ISSUE THREAD

**Issue by juherr** [testng-team/testng-team.github.io#16]
.

**Comment by cbeust** [comment]
Why `[EPIC]`?

**Comment by juherr** [comment]
@cbeust Because I plan to collect missing documentation here.

**Comment by krmahadevan** [comment]
@juherr - Do we still need this? If there are missing aspects in the documentation, it would be good if we can just track them as individual issues [ I dont think Github supports the notion of epic, story, sub-task etc., ]

**Comment by juherr** [comment]
Sure. Close it when/if it is resolved

**Comment by krmahadevan** [comment]
Details are available here https://testng.org/#_parameters_with_dataproviders
