### ISSUE TITLE
[Proposal] To add TestNG GitHub repo's link to documentation's top menu

### ISSUE THREAD

**Issue by mohsinsackeer** [testng-team/testng-team.github.io#48]
I have been going through TestNG's documentation, and wanted to checkout the GitHub Repo, but couldn't find it's link in the page. 

For convenience, and for making it easy for people to contribute to TestNG, I would suggest adding a GitHub Repo link.

**Comment by juherr** [comment]
It already is: https://testng.org/doc/download.html
![image](https://github.com/testng-team/testng-team.github.io/assets/254697/f4d2206c-a0ef-40d0-a9d9-db6938031bea)

But feel free to propose any improvements and/or update to the new url

**Comment by mohsinsackeer** [comment]
The idea I had in mind was to include a GitHub link in the Top Menu.
![TestNG Screenshot](https://github.com/testng-team/testng-team.github.io/assets/66770253/abf321e7-8b5a-4a03-b712-1af0ec0bc3df)

Here, we could add the link to the right of Selenium and to the top of Kobalt.
