### ISSUE TITLE
Group documentation of runners under the same section

### ISSUE THREAD

**Issue by juherr** [testng-team/testng-team.github.io#71]
* Test runners
  * [Eclipse plug-in](https://testng.org/#_eclipse_plug_in_2)
  * [TestNG IDEA Plug-in](https://testng.org/#_testng_idea_plug_in)
  * [Using TestNG with Gradle](https://testng.org/#_using_testng_with_gradle)
  * [Using TestNG with Maven](https://testng.org/#_using_testng_with_maven)
  * [TestNG Ant Task](https://testng.org/#_testng_ant_task)
  * [Running TestNG programmatically](https://testng.org/#_running_testng_programmatically)

**Comment by krmahadevan** [comment]
All the above mentioned topics are now grouped under https://testng.org/#_running_testng_2
