### ISSUE TITLE
Move eclipse documentation to eclipse repository

### ISSUE THREAD

**Issue by juherr** [testng-team/testng-team.github.io#73]
1. Enable github pages in eclipse repository (maybe a docs folder on main branch)
2. Move dedicated documentation there

**Comment by juherr** [comment]
I migrated 2 pages:
https://testng.org/testng-eclipse/
and
https://testng.org/testng-eclipse/download

There are some link and display issues.

Sadly, I had to move to markdown because github pages don't support adoc: https://github.com/orgs/community/discussions/36737
I think it should be possible later to use an action to convert adoc files from a folder into HTML and push them in the `github-page` branch: https://github.com/asciidoctor/jekyll-asciidoc-quickstart or https://github.com/manoelcampos/asciidoctor-ghpages-action

@krmahadevan wdyt?

**Comment by krmahadevan** [comment]
@juherr - I don't have any specific preferences in terms of asciidocs or markdown. As long as the documentation is there and it's easy for contributors to help enhance it, I am fine.
